apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jm-backstage-web-bff-service
  description: Entry point for the e-commerce website
  tags:
    - web
    - bff
  annotations:
    github.com/project-slug: aquijun/jm-backstage-web-bff-service
spec:
  type: service
  owner: team-ecommerce
  lifecycle: experimental
  repository: https://github.com/aquijun/jm-backstage-web-bff-service.git
  providesApis:
    - web-bff-api
  consumesApis:
    - product-api
    - order-api
    - user-api
  dependsOn:
    - Component: jm-backstage-product-service
  #   - component: jm-backstage-order-service
  #   - component: jm-backstage-user-service

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: web-bff-api
  description: This is a sample API
  tags:
    - web-bff
    - api
spec:
  type: openapi
  lifecycle: experimental
  owner: team-ecommerce
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths:
      /:
        get:
          summary: Sample endpoint
          responses:
            '200':
              description: Successful response
